In [3]:
import pandas as pd
import numpy as np
from sklearn.covariance import LedoitWolf
from scipy.optimize import minimize

pd.set_option('display.max_columns', None)

In [42]:
def read_Bloomberg_port(fn):
  df_2023 = pd.read_excel(fn, skiprows=2)
  col_mapping = {
      'Ticker': 'Ticker',
      'Short Name': 'ShortName',
      'PORT US Sz Fact Exp:D-1': 'Size',
      'PORT US Prof Fact Exp:D-1': 'Profitability',
      'PORT US Vol Fact Exp:D-1': 'Volatility',
      'PORT US Trd Act Fact Exp:D-1': 'TradingActivity',
      'PORT US Lev Fact Exp:D-1': 'Leverage',
      'PORT US Mom Fact Exp:D-1': 'Momentum',
      'PORT US Val Fact Exp:D-1': 'Value',
      'PORT US Gr Fact Exp:D-1': 'Growth',
      'PORT US Dvd Yld Fact Exp:D-1': 'DividendYield',
      'PORT US Earn Var Fact Exp:D-1': 'EarningsVariation',
      'P/S': 'PriceToSales',
      'BEst P/S BF12M': 'EstPriceToSales',
      'P/B': 'PriceToBook',
      'BEst P/B BF12M': 'EstPriceToBook',
      'P/E': 'PriceToEarnings',
      'BEst P/E BF12M': 'EstPriceToEarnings',
      'ROE LF': 'ReturnOnEquity',
      'T12M R&D/Sls': 'RnDToSales',
      'GICS Sector': 'Sector',
      'GICS Ind': 'Industry',
      'GICS SubInd': 'SubIndustry',
      'GICS Sector.1': 'SectorName',
      'GICS Ind Name': 'IndustryName',
      'GICS SubInd Name': 'SubIndustryName',
      'ESG Disclosure Score (Latest Available) (BLOOMBERG L.P.)': 'ESGScore',
      'Beta:Y-1': 'Beta',
      'Total Return:Y-1': 'Return1Yr',
      'Number of Employees:Y': 'NumberOfEmployees',
      'Number of Employees:Y-5': 'NumberOfEmployees5YearsAgo'
  }
  df_2023 = df_2023.loc[~df_2023['Short Name'].isna()]
  df_2023.rename(columns=col_mapping, inplace=True)
  df_2023.drop(columns=['Ticker.1'], inplace=True)
  df_2023.drop(df_2023[df_2023['ShortName'].str.contains('ADR')].index, inplace=True)
  df_2023.Ticker=df_2023.Ticker.map(lambda s: s.split(' ')[0])
  df_2023 = df_2023.loc[df_2023.Ticker.map(len)<=4]
  return df_2023

df_2023 = read_Bloomberg_port('data/original_data/20230101_SimplePort.xlsx')
df_2024 = read_Bloomberg_port('data/original_data/20240101_SimplePort.xlsx')
df_2023_tmp = read_Bloomberg_port('data/original_data/20230101_SimplePort.xlsx')
sec2sec_name = df_2023_tmp.set_index('Sector')['SectorName'].to_dict()
secname2sec = df_2023_tmp.set_index('SectorName')['Sector'].to_dict()

In [43]:
df_2024.columns

Index(['Ticker', 'ShortName', 'Size', 'Profitability', 'Volatility',
       'TradingActivity', 'Leverage', 'Momentum', 'Value', 'Growth',
       'DividendYield', 'EarningsVariation', 'PriceToSales', 'EstPriceToSales',
       'PriceToBook', 'EstPriceToBook', 'PriceToEarnings',
       'EstPriceToEarnings', 'ReturnOnEquity', 'RnDToSales', 'Sector',
       'Industry', 'SubIndustry', 'SectorName', 'IndustryName',
       'SubIndustryName', 'ESGScore', 'Beta', 'Return1Yr', 'NumberOfEmployees',
       'NumberOfEmployees5YearsAgo'],
      dtype='object')

In [49]:
df_2024

,Ticker,ShortName,Size,Profitability,Volatility,TradingActivity,Leverage,Momentum,Value,Growth,DividendYield,EarningsVariation,PriceToSales,EstPriceToSales,PriceToBook,EstPriceToBook,PriceToEarnings,EstPriceToEarnings,ReturnOnEquity,RnDToSales,Sector,Industry,SubIndustry,SectorName,IndustryName,SubIndustryName,ESGScore,Beta,Return1Yr,NumberOfEmployees,NumberOfEmployees5YearsAgo
4,AAL,AMERICAN AIRLINE,-0.872789,-0.884676,-0.961996,3.000228,2.427836,-0.610635,2.050937,-0.812962,-0.722812,0.138502,0.169481,0.163585,NaN,NaN,4.043788,6.773244,NaN,NaN,20.0,203020.0,20302010.0,Industrials,Passenger Airlines,Passenger Airlines,65.878685,1.227147,8.188976,129700.0,126600.0
5,AAPL,APPLE INC,1.973204,2.738760,0.495583,-0.478149,0.085498,-0.130112,-0.372220,0.031300,-0.472168,0.460963,7.914328,7.466528,48.174509,40.067432,31.459150,28.716615,171.949509,8.071053,45.0,452020.0,45202030.0,Information Technology,"Technology Hardware, Storage & Peripherals","Technology Hardware, Storage & Peripherals",57.318176,1.075160,49.371970,161000.0,132000.0
8,ABBV,ABBVIE INC,0.496940,1.530953,0.124997,-0.728043,0.839538,-0.148440,0.063431,-0.557802,1.094617,-0.410797,4.976616,5.115141,22.782770,18.597456,18.267769,13.823277,46.069496,22.705648,35.0,352010.0,35201010.0,Health Care,Biotechnology,Biotechnology,69.017204,0.468575,-0.810278,50000.0,29000.0
11,ABNB,AIRBNB INC-A,-0.819412,0.108318,-0.543316,1.690136,-0.697833,-0.036284,-0.447422,1.276618,-0.722812,1.897143,9.023584,8.042780,9.669924,7.524665,16.481900,29.302311,74.472473,18.519186,25.0,253010.0,25301020.0,Consumer Discretionary,"Hotels, Restaurants & Leisure","Hotels, Resorts & Cruise Lines",42.510815,1.466884,59.732482,6811.0,NaN
12,ABT,ABBOTT LABS,0.098690,-0.457890,-0.388962,-0.784018,-0.477903,-0.687410,-0.191666,-0.600183,0.244200,-0.375825,4.803144,4.586008,5.098262,4.964078,33.691698,23.822355,14.112308,6.779499,35.0,351010.0,35101010.0,Health Care,Health Care Equipment & Supplies,Health Care Equipment,79.629814,0.718053,1.781966,115000.0,99000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
684,WMT,WALMART INC,1.390133,-0.755175,-0.034558,-0.883312,-0.200955,0.060899,0.007342,-0.478348,-0.080722,-0.324086,0.664872,0.638207,5.343227,4.635032,23.958965,22.375866,21.477961,0,30.0,301010.0,30101040.0,Consumer Staples,Consumer Staples Distribution & Retail,Consumer Staples Merchandise Retail,54.471382,0.591213,12.599971,2100000.0,2300000.0
687,XEL,XCEL ENERGY INC,-0.731118,-0.785769,-0.226984,-0.110820,1.115379,-1.180554,0.434117,-0.838571,0.942531,-0.913837,2.300985,2.172828,1.973161,1.829384,19.304255,17.309397,10.334491,NaN,55.0,551010.0,55101010.0,Utilities,Electric Utilities,Electric Utilities,71.884117,0.673637,-9.926571,11982.0,11075.0
690,XOM,EXXON MOBIL CORP,1.375566,-0.080958,0.202097,-0.457229,-0.826035,0.131019,0.967992,-0.498213,0.757364,0.519116,1.179272,1.146779,1.984050,1.730857,9.590236,10.817643,21.321762,NaN,10.0,101020.0,10102010.0,Energy,"Oil, Gas & Consumable Fuels",Integrated Oil & Gas,66.230759,0.696742,-5.299010,62000.0,69600.0
691,XYZ,BLOCK INC,-0.932959,-1.413631,-0.066629,3.000228,-0.566332,-1.311343,-0.249530,1.817979,-0.722812,0.570095,2.233461,1.926434,2.661211,2.421789,NaN,24.559298,-0.973276,12.082453,40.0,402010.0,40201060.0,Financials,Financial Services,Transaction & Payment Processing Services,45.991348,1.777374,22.933885,12428.0,2338.0
699,ZTS,ZOETIS INC,-0.978841,0.440940,0.554436,-0.514497,0.476610,-0.087967,-0.458439,-0.351573,-0.325065,-0.686265,10.910983,9.859355,17.860653,14.556812,38.908403,32.657849,46.812443,7.411409,35.0,352020.0,35202010.0,Health Care,Pharmaceuticals,Pharmaceuticals,54.551857,1.004428,34.431441,13800.0,9200.0

In [35]:
df_2024[["Ticker",	"ShortName",	"Size",	"Profitability",	"Volatility",	"TradingActivity",	"Leverage",	"Momentum",	"Value",	"Growth", "Return1Yr"]]

,Ticker,ShortName,Size,Profitability,Volatility,TradingActivity,Leverage,Momentum,Value,Growth,Return1Yr
4,AAL,AMERICAN AIRLINE,-0.872789,-0.884676,-0.961996,3.000228,2.427836,-0.610635,2.050937,-0.812962,8.188976
5,AAPL,APPLE INC,1.973204,2.738760,0.495583,-0.478149,0.085498,-0.130112,-0.372220,0.031300,49.371970
8,ABBV,ABBVIE INC,0.496940,1.530953,0.124997,-0.728043,0.839538,-0.148440,0.063431,-0.557802,-0.810278
11,ABNB,AIRBNB INC-A,-0.819412,0.108318,-0.543316,1.690136,-0.697833,-0.036284,-0.447422,1.276618,59.732482
12,ABT,ABBOTT LABS,0.098690,-0.457890,-0.388962,-0.784018,-0.477903,-0.687410,-0.191666,-0.600183,1.781966
...,...,...,...,...,...,...,...,...,...,...,...
684,WMT,WALMART INC,1.390133,-0.755175,-0.034558,-0.883312,-0.200955,0.060899,0.007342,-0.478348,12.599971
687,XEL,XCEL ENERGY INC,-0.731118,-0.785769,-0.226984,-0.110820,1.115379,-1.180554,0.434117,-0.838571,-9.926571
690,XOM,EXXON MOBIL CORP,1.375566,-0.080958,0.202097,-0.457229,-0.826035,0.131019,0.967992,-0.498213,-5.299010
691,XYZ,BLOCK INC,-0.932959,-1.413631,-0.066629,3.000228,-0.566332,-1.311343,-0.249530,1.817979,22.933885
699,ZTS,ZOETIS INC,-0.978841,0.440940,0.554436,-0.514497,0.476610,-0.087967,-0.458439,-0.351573,34.431441

In [18]:
df_2024.describe()

,Size,Profitability,Volatility,TradingActivity,Leverage,Momentum,Value,Growth,DividendYield,EarningsVariation,PriceToSales,EstPriceToSales,PriceToBook,EstPriceToBook,PriceToEarnings,EstPriceToEarnings,ReturnOnEquity,Sector,Industry,SubIndustry,ESGScore,Beta,Return1Yr,NumberOfEmployees,NumberOfEmployees5YearsAgo
count,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,2.850000e+02,284.000000,2.690000e+02,268.000000,275.000000,284.000000,265.000000,288.000000,288.000000,2.880000e+02,285.000000,297.000000,296.000000,2.820000e+02,2.750000e+02
mean,-0.256936,-0.398760,-0.120091,0.003761,0.286881,-0.248938,0.432433,-0.366054,0.460788,-0.213425,3.333612e+00,3.233990,7.481286e+00,5.272274,29.690311,17.938492,27.700041,33.055556,332338.975694,3.323392e+07,59.346354,0.698053,17.322069,8.667503e+04,7.666286e+04
std,0.618966,0.822383,0.679813,0.823292,0.818269,0.789721,0.819419,0.804089,0.957027,0.834400,3.574836e+00,3.028185,1.935655e+01,8.776850,94.961121,10.527929,76.450272,13.272947,132796.769058,1.327967e+07,11.124894,8.376645,36.218545,1.770887e+05,1.620598e+05
min,-0.995107,-3.000278,-2.301204,-0.989573,-1.381528,-3.000094,-3.000008,-2.159863,-1.077917,-1.099723,8.116883e-07,0.105223,1.926285e-08,0.364793,2.417327,3.858827,-78.914246,10.000000,101010.000000,1.010102e+07,19.897394,-123.384805,-99.000000,5.000000e+00,3.000000e+00
25%,-0.746991,-0.876446,-0.455339,-0.479537,-0.325458,-0.687410,-0.142042,-0.887097,-0.241258,-0.858323,1.198498e+00,1.308564,1.640124e+00,1.509114,11.266626,10.747454,10.021650,20.000000,203035.000000,2.030351e+07,52.801529,0.715129,-2.342056,1.827500e+04,1.430000e+04
50%,-0.377920,-0.486944,-0.105274,-0.222741,0.204379,-0.241731,0.217729,-0.569446,0.276729,-0.503253,2.087949e+00,2.352398,2.796241e+00,2.468004,17.841822,15.705487,16.151398,35.000000,352010.000000,3.520101e+07,60.004025,0.934107,11.257431,4.392300e+04,3.648400e+04
75%,0.088826,0.000000,0.180620,0.154117,0.874665,0.209769,0.811163,0.000000,1.021884,0.148771,4.223761e+00,3.983458,6.353123e+00,5.131749,25.816680,21.690061,27.757156,40.000000,403010.000000,4.030102e+07,67.458000,1.140786,26.272791,8.904850e+04,8.090000e+04
max,1.973204,2.881678,2.342157,3.000330,2.427836,3.000132,3.000015,3.000005,3.000010,3.000093,2.725291e+01,15.627382,2.413733e+02,91.445468,1437.913168,72.384421,1151.319702,60.000000,602010.000000,6.020104e+07,85.434059,72.385598,239.274541,2.100000e+06,2.300000e+06

In [19]:
df_2024.sort_values(by="Volatility", ascending=True).head(10)

,Ticker,ShortName,Size,Profitability,Volatility,TradingActivity,Leverage,Momentum,Value,Growth,DividendYield,EarningsVariation,PriceToSales,EstPriceToSales,PriceToBook,EstPriceToBook,PriceToEarnings,EstPriceToEarnings,ReturnOnEquity,RnDToSales,Sector,Industry,SubIndustry,SectorName,IndustryName,SubIndustryName,ESGScore,Beta,Return1Yr,NumberOfEmployees,NumberOfEmployees5YearsAgo
454,MU,MICRON TECH,-0.380408,-1.386005,-2.301204,1.686383,-0.397905,0.440698,-0.404964,1.088885,-0.416592,0.345225,5.776736,3.684479,2.184990,2.085782,NaN,43.185004,-14.908180,11.937169,45.0,453010.0,45301020.0,Information Technology,Semiconductors & Semiconductor Equipment,Semiconductors,63.796398,1.232522,70.037281,43000.0,36000.0
119,CAH,CARDINAL HEALTH,-0.364561,-1.182482,-2.065425,0.557005,0.536164,0.446375,0.094259,0.922200,0.298332,0.791167,0.122213,0.105223,NaN,NaN,12.609689,13.704304,NaN,0,35.0,351020.0,35102010.0,Health Care,Health Care Providers & Services,Health Care Distributors,59.561413,0.659773,33.510477,47040.0,50200.0
65,AZO,AUTOZONE INC,-0.964473,0.188525,-1.646327,0.327311,1.544852,0.039778,-0.090397,-0.089951,-0.722812,-0.169846,2.662459,2.356317,NaN,NaN,18.767585,16.817097,NaN,NaN,25.0,255040.0,25504050.0,Consumer Discretionary,Specialty Retail,Automotive Retail,55.416962,0.722825,4.919299,71400.0,54900.0
502,PCG,PG&E CORP,-0.452164,-0.925849,-1.633861,0.279283,1.613480,0.322913,0.591981,-0.455829,-0.722812,0.267317,1.605463,1.556669,1.485155,1.381260,14.773264,13.355556,7.919596,NaN,55.0,551010.0,55101010.0,Utilities,Electric Utilities,Electric Utilities,67.166283,0.694938,10.403780,10.0,23000.0
105,BNS,BANK OF NOVA SCO,0.501197,-1.009744,-1.563583,-0.357506,-0.960169,-0.625248,0.483818,-0.821158,2.528946,-0.890482,1.090242,2.299149,1.137291,1.081291,10.958598,9.814938,10.434095,NaN,40.0,401010.0,40101010.0,Financials,Banks,Diversified Banks,56.392715,1.021457,5.543409,89483.0,97629.0
495,ORLY,O'REILLY AUTOMOT,-0.976754,0.427109,-1.559962,0.067214,1.203269,0.417605,-0.205464,-0.004848,-0.722812,0.125093,3.724850,3.352287,NaN,NaN,25.274807,22.258980,NaN,NaN,25.0,255040.0,25504050.0,Consumer Discretionary,Specialty Retail,Automotive Retail,46.333366,0.599067,12.614092,87745.0,45440.0
498,OXY,OCCIDENTAL PETE,-0.348333,-0.037208,-1.533463,1.949072,0.369330,-0.633844,1.348544,-0.181526,-0.179088,0.656377,1.824577,1.689468,2.785858,2.145272,13.175230,11.523112,23.674873,0,10.0,101020.0,10102010.0,Energy,"Oil, Gas & Consumable Fuels",Integrated Oil & Gas,70.988831,0.798361,-2.974148,11973.0,11000.0
162,COR,CENCORA INC,-0.043906,0.682174,-1.489687,-0.057942,0.161707,0.291540,0.186928,1.115700,-0.241258,0.829328,0.158613,0.141979,79.009781,22.908188,19.327647,15.545859,NaN,0,35.0,351020.0,35102010.0,Health Care,Health Care Providers & Services,Health Care Distributors,56.543606,0.469938,25.068264,46000.0,20000.0
617,TD,TORONTO-DOM BANK,0.905939,-0.948231,-1.426865,-0.479537,-1.084829,-0.517382,-0.118421,-0.859420,1.494274,-0.947067,1.541291,3.015338,1.514209,1.400221,11.360937,10.735469,10.021650,NaN,40.0,401010.0,40101010.0,Financials,Banks,Diversified Banks,62.428326,0.938697,3.560005,103257.0,86588.0
539,REGN,REGENERON PHARM,-0.617505,-0.065605,-1.425192,-0.215812,-1.026233,-0.005110,-0.103921,0.525941,-0.722812,1.155375,7.164799,6.995486,3.836991,3.241473,22.209010,20.009522,17.224102,36.135756,35.0,352010.0,35201010.0,Health Care,Biotechnology,Biotechnology,61.351978,0.671045,21.766558,11851.0,6200.0

In [25]:
df_2024.columns

Index(['Ticker', 'ShortName', 'Size', 'Profitability', 'Volatility',
       'TradingActivity', 'Leverage', 'Momentum', 'Value', 'Growth',
       'DividendYield', 'EarningsVariation', 'PriceToSales', 'EstPriceToSales',
       'PriceToBook', 'EstPriceToBook', 'PriceToEarnings',
       'EstPriceToEarnings', 'ReturnOnEquity', 'RnDToSales', 'Sector',
       'Industry', 'SubIndustry', 'SectorName', 'IndustryName',
       'SubIndustryName', 'ESGScore', 'Beta', 'Return1Yr', 'NumberOfEmployees',
       'NumberOfEmployees5YearsAgo'],
      dtype='object')

In [20]:
df_2023.loc[df_2023.Ticker.map(len)<=4]

,Ticker,ShortName,Size,Profitability,Volatility,TradingActivity,Leverage,Momentum,Value,Growth,DividendYield,EarningsVariation,PriceToSales,EstPriceToSales,PriceToBook,EstPriceToBook,PriceToEarnings,EstPriceToEarnings,ReturnOnEquity,RnDToSales,Sector,Industry,SubIndustry,SectorName,IndustryName,SubIndustryName,ESGScore,Beta,Return1Yr,NumberOfEmployees,NumberOfEmployees5YearsAgo
6,AAL,AMERICAN AIRLINE,-0.719767,-1.341221,-1.105211,3.000263,2.426632,-0.375821,-0.823127,-0.120481,-0.817272,0.146493,0.182858,0.163673,NaN,NaN,NaN,8.579747,NaN,NaN,20.0,203020.0,20302010.0,Industrials,Passenger Airlines,Passenger Airlines,63.524796,1.366619,-29.607081,123400.0,122300.0
7,AAPL,APPLE INC,1.957850,2.593115,0.374834,-0.259648,0.167017,-0.259431,-0.242191,0.108389,-0.463189,0.372328,5.348388,5.030219,40.881141,32.346441,21.265138,20.483301,175.459290,8.071053,45.0,452020.0,45202030.0,Information Technology,"Technology Hardware, Storage & Peripherals","Technology Hardware, Storage & Peripherals",57.841263,1.204978,-26.664348,164000.0,123000.0
11,ABBV,ABBVIE INC,0.682031,1.660152,0.295544,-0.605930,0.745129,1.082947,-0.080965,-0.224200,0.952905,-0.392500,4.954442,5.260390,17.868656,10.507730,15.813123,13.826323,90.346603,22.705648,35.0,352010.0,35201010.0,Health Care,Biotechnology,Biotechnology,68.735542,0.565296,23.556542,50000.0,30000.0
16,ABNB,AIRBNB INC-A,-0.869328,-0.247090,-1.233799,2.482911,-0.677831,-1.205130,-0.400091,0.640439,-0.817272,2.095078,6.774357,5.879248,9.777071,6.638529,32.793513,28.543442,32.622395,18.519186,25.0,253010.0,25301020.0,Consumer Discretionary,"Hotels, Restaurants & Leisure","Hotels, Resorts & Cruise Lines",34.503571,1.497668,-49.342339,6132.0,NaN
17,ABT,ABBOTT LABS,0.312303,-0.109193,-0.339526,-0.696387,-0.493004,-0.216173,-0.221073,-0.725278,0.100462,-0.229170,4.298149,4.862459,5.365857,4.930816,23.473882,24.941718,22.508808,6.779499,35.0,351010.0,35101010.0,Health Care,Health Care Equipment & Supplies,Health Care Equipment,78.905540,0.887124,-20.834801,113000.0,75000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
926,WTW,WILLIS TOWERS WA,-0.894190,-0.446810,-0.761553,0.161237,-0.348832,0.330909,-0.110303,-0.689373,-0.159082,-0.705590,3.224881,2.893882,2.700995,2.950068,21.006516,16.254338,26.593189,NaN,40.0,403010.0,40301010.0,Financials,Insurance,Insurance Brokers,36.535561,0.877496,4.693283,44000.0,41000.0
927,XEL,XCEL ENERGY INC,-0.483149,-0.740004,-0.203117,-0.184181,0.898300,0.427947,0.067726,-0.700532,0.523147,-0.927662,2.615653,2.699165,2.340735,2.203627,22.911765,20.776851,10.597370,NaN,55.0,551010.0,55101010.0,Utilities,Electric Utilities,Electric Utilities,71.833817,0.657713,5.641302,11321.0,11075.0
930,XOM,EXXON MOBIL CORP,1.486901,-0.118543,0.061943,-0.215250,-0.833794,1.782989,0.923906,-0.866065,0.811943,0.411162,1.207891,1.202259,2.440706,2.119010,8.719355,9.793259,29.917303,NaN,10.0,101020.0,10102010.0,Energy,"Oil, Gas & Consumable Fuels",Integrated Oil & Gas,67.618950,0.690480,88.588112,63000.0,71100.0
931,XYZ,BLOCK INC,-0.678655,-1.298511,0.307278,3.000263,-0.637994,-1.498321,-0.497665,2.561815,-0.817272,0.935745,2.005896,1.880089,2.272224,2.685771,NaN,37.005205,-5.177986,12.082453,40.0,402010.0,40201060.0,Financials,Financial Services,Transaction & Payment Processing Services,46.454079,2.204972,-61.993467,8521.0,1853.0
941,ZTS,ZOETIS INC,-0.839229,0.270564,-0.507151,-0.466519,0.146671,-0.820801,-0.463844,-0.154627,-0.311368,-0.606579,8.615981,7.979552,14.659466,11.862062,31.421150,27.340466,44.251766,7.411409,35.0,352020.0,35202010.0,Health Care,Pharmaceuticals,Pharmaceuticals,50.970726,0.976887,-39.782111,12100.0,9000.0

In [21]:
prc_df_2023 = pd.read_parquet('data/original_data/prc_df_2023.parquet')
prc_df_2023 = prc_df_2023.dropna(axis=1)

In [22]:
prc_df_2023

Ticker,AAL,AAPL,ABBV,ABNB,ABT,ACGL,ACI,ACN,ADBE,ADI,ADM,ADP,AEE,AEP,AER,AES,AFL,AGR,AIG,AJG,ALC,ALL,ALLY,AMAT,AMD,AMGN,AMP,AMT,AMZN,AON,APD,APH,APO,ASML,AVGO,AXP,AZO,BA,BAC,BAX,BBY,BCE,BDX,BHF,BIIB,BK,BKNG,BKR,BMO,BMY,BN,BNS,BSX,BX,C,CAH,CARR,CAT,CB,CBRE,CCEP,CCI,CDW,CEG,CFG,CHTR,CI,CL,CM,CME,CMI,CNC,CNH,CNI,CNP,CNQ,COF,COP,COR,COST,CP,CRH,CRM,CSCO,CSX,CTSH,CTVA,CVE,CVS,CVX,D,DAL,DB,DD,DE,DELL,DFS,DG,DHI,DHR,DIS,DLR,DLTR,DOW,DTE,DUK,DVN,ECL,ED,EG,EIX,EL,ELV,EMR,ENB,EOG,EPD,EQH,EQIX,ES,ET,ETN,ETR,EXC,F,FANG,FCX,FDX,FE,FERN,FI,FIS,FITB,FNF,FNRC,FRCB,FTS,GD,GE,GILD,GIS,GLW,GM,GOLD,GOOG,GPC,GPN,GS,HAL,HBAN,HCA,HD,HES,HIG,HON,HPE,HPQ,HSY,HUM,IBKR,IBM,ICE,IFF,IMO,INTC,INTU,IQV,ISRG,ITW,JCI,JNJ,JPM,JXN,K,KDP,KEY,KHC,KKR,KLAC,KMB,KMI,KMX,KO,KR,L,LEN,LHX,LLY,LMT,LNC,LNG,LOW,LRCX,LUV,LYB,LYG,MA,MAR,MCD,MCHP,MCK,MCO,MDLZ,MDT,MELI,MET,META,MFC,MGA,MGM,MKL,MMC,MMM,MO,MOH,MOS,MPC,MPLX,MRK,MRNA,MS,MSFT,MT,MTB,MU,NEE,NEM,NFLX,NKE,NOC,NOW,NSC,NTR,NTRS,NUE,NVDA,NXPI,O,OKE,ORCL,ORLY,OXY,PAA,PARA,PCAR,PCG,PDD,PEG,PEP,PFE,PFG,PG,PGR,PH,PHG,PLD,PM,PNC,PPG,PPL,PRU,PSX,PYPL,QCOM,REGN,RF,RGA,RJF,ROP,ROST,RSG,RTX,RY,SBUX,SCCO,SCHW,SHW,SLB,SLF,SNX,SO,SPG,SPGI,SPRV,SRE,STLA,STM,STT,STZ,SU,SVXY,SYF,SYK,SYY,T,TD,TECK,TFC,TGT,TJX,TMO,TMUS,TRGP,TRP,TRV,TSLA,TSN,TT,TU,TXN,UAL,UBER,UNH,UNP,UPS,URI,USB,UVXY,V,VIXM,VIXY,VLO,VRTX,VTRS,VXX,VXZ,VZ,WBA,WBD,WEC,WELL,WFC,WM,WMB,WMT,WRB,WTW,XEL,XOM,XYZ,ZTS
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-01-03,12.74,123.632523,149.164108,84.900002,104.779053,59.393120,19.611376,261.824371,336.920013,156.755081,83.634407,227.386276,82.914330,86.777695,57.485336,25.735664,68.086044,39.008400,60.120926,183.706192,68.536598,129.909256,22.488546,94.880524,64.019997,243.500778,300.683563,200.793762,85.820000,294.697968,291.319366,37.503994,60.327297,539.838257,53.397110,142.924423,2431.060059,195.389999,31.691650,48.181396,73.375404,37.612625,248.158539,51.040001,272.630005,43.170719,2014.349731,27.223515,82.620468,65.689964,31.083275,42.613499,46.009998,71.071815,41.898056,73.629539,40.473133,229.551056,214.210449,78.440002,51.223434,123.322502,174.761917,80.366318,35.463558,341.579987,310.605743,75.046204,36.710869,153.949326,227.850983,79.739998,15.041700,115.038155,27.779707,23.747482,89.124313,105.279388,160.675415,436.833771,73.958015,38.840900,134.031387,44.742989,30.033775,55.511196,57.571247,17.394024,85.305573,158.737137,56.787544,32.027203,11.027692,66.211334,412.431000,38.959743,92.037918,237.219025,88.852730,230.468842,87.884308,95.622894,140.259995,45.894928,109.783836,94.552734,52.896431,144.011230,88.496017,322.539856,59.005463,244.567307,489.243286,91.732132,34.593353,114.444595,20.580132,27.092442,633.336914,77.240532,9.589602,153.045151,46.888412,39.623119,9.566102,119.176521,36.758308,170.126160,38.218536,0.00140,101.209999,64.903152,29.949360,34.804111,0.0001,121.299080,37.304901,236.807236,52.438713,78.986496,77.185219,30.512453,33.117290,17.100534,89.378845,160.833694,98.420326,327.647125,36.224506,12.770592,239.135498,300.008942,131.113815,72.287659,205.286530,15.163097,24.961742,214.306854,491.160400,70.599174,129.286346,100.416870,99.560631,44.127991,25.775145,385.398315,203.860001,265.630005,210.635574,61.830021,166.303711,127.490326,31.245569,62.280090,33.548054,15.624210,37.219692,45.816761,367.926422,127.417076,15.775637,60.639999,59.216160,42.229450,58.123062,86.386391,197.872818,358.463654,453.063049,26.606739,137.336670,190.490509,37.085289,30.993149,75.341171,2.006593,342.209991,144.444031,252.362473,65.765678,370.442841,271.165344,63.049377,73.202179,826.109985,67.221916,124.265312,16.459894,53.372166,33.279999,1321.969971,160.665405,92.868958,38.414948,318.920013,40.331993,105.604301,26.856091,105.242310,178.990005,79.096329,235.240036,25.641068,134.905746,49.810669,79.221115,46.492268,294.950012,115.257530,522.815002,385.500000,234.907440,66.232445,83.635704,127.500748,14.304594,150.005295,56.927864,56.891449,81.271118,840.719971,59.369766,9.746503,16.393124,60.039436,15.625342,84.529999,57.893932,168.991745,45.458897,78.064346,143.352737,126.501328,283.433716,15.640000,106.143532,91.362938,145.359940,121.228485,27.185762,89.058975,93.200310,74.580002,102.387222,719.545288,19.554483,135.257324,102.882286,428.799500,113.353355,125.470375,95.494362,87.339005,95.728004,56.184788,79.137817,235.046265,48.942047,43.350952,93.605820,66.060257,105.035805,328.799652,0.00015,72.084137,12.517066,34.929192,73.028488,219.467392,27.871864,29.434999,30.632381,241.189270,71.495941,16.329086,57.466839,35.328564,38.457619,141.533371,76.503517,550.206543,136.423096,67.232208,34.501629,179.657333,108.099998,59.320129,167.506516,17.299818,152.731262,37.209999,25.360001,503.071106,198.088806,158.550125,347.738922,40.407875,339.500000,203.852264,29.870001,226.600006,112.000549,286.019989,10.421737,223.839996,101.959999,34.429863,32.070896,9.54,86.703087,63.172703,39.284389,152.102371,29.120783,46.589111,45.902946,238.615936,65.245399,98.713264,64.639999,143.661133
2023-01-04,13.59,124.907700,150.367462,88.720001,106.337631,59.687901,19.800861,260.933105,341.410004,160.093781,80.593147,228.457870,83.354713,87.372246,59.003067,24.975773,68.409447,39.532848,61.009415,186.139160,69.818298,132.095642,23.243689,97.411201,64.660004,246.050751,302.832306,204.843872,85.139999,297.945892,291.338379,38.058697,61.816029,560.721863,54.049294,146.246887,2445.459961,203.639999,32.287472,49.399143,74.771538,38.355320,250.008743,52.139999,270.809998,44.233677,2091.892334,26.409178,84.970932,66.017220,32.403038,44.016968,46.500000,72.826897,42.978001,73.888618,40.881653,231.934204,217.732559,79.720001,52.448429,127.816360,176.358521,81.838051,36.468349,354.000000,299.803894,75.529892,37.616863,154.979019,227.302765,79.459999,15.097721,116.785400,27.864286,23.802116,91.837257,105.484116,159.286667,439.994781,75.745735,40.705791,138.814651,44.733578,30.422815,55.964226,58.313721,17.279654,84.451683,157.049301,57.003983,33.775387,11.752826,67.817085,411.643646,38.997841,96.099388,234.123032,89.793373,234.071701,90.857590,96.385422,140.520004,47.054890,111.367348,95.564827,53.606331,146.505814,89.263054,329.999146,60.942322,252.272949,472.915680,91.073570,35.249233,114.361847,20.673561,28.106043,650.200256,78.258545,9.622613,154.083221,46.922787,40.146408,9.836378,118.487099,37.805233,174.137695,38.500427,0.00145,102.059998,65.594406,30.701763,35.485279,0.0001,123.544624,37.719398,233.587601,55.490860,79.088257,77.806633,31.984636,33.969212,18.107573,88.392403,162.851120,101.642075,329.047760,36.965157,13.006078,244.710495,303.636627,133.111893,73.697906,201.205719,15.502995,25.400322,210.850433,482.946411,71.331085,130.245422,101.097786,101.935608,43.984871,26.691208,385.782623,207.779999,270.000000,211.113617,62.842381,168.114288,128.679199,31.732794,61.808197,33.821716,16.041210,37.639534,47.210503,371.522125,127.138283,15.968342,65.120003,59.187931,42.704258,58.797638,87.917259,197.872818,356.607422,452.085846,27.167875,141.402145,192.739578,37.815716,31.962864,77.054512,2.051383,350.449554,146.506805,252.419830,67.374123,370.126129,278.658813,63.506199,75.737045,837.440002,68.190880,126.885315,16.875547,55.172264,35.540001,1348.000000,163.791946,94.901199,38.322124,313.529999,40.937489,105.280609,27.053919,106.132446,177.360001,79.954453,224.949890,26.459499,136.413269,53.598141,79.844826,48.302067,309.410004,117.645180,509.385010,393.850006,237.942169,66.565376,85.405678,133.279419,14.738280,152.820648,57.650623,57.336334,82.008911,826.739990,59.428116,9.746503,17.766417,59.905235,15.824645,91.059998,58.323116,168.577286,44.456787,79.219894,143.976974,127.570595,288.417328,16.260000,110.165482,91.299797,149.196228,124.220009,27.865404,90.580879,92.877434,77.690002,106.522842,725.557617,19.955229,135.927246,102.329628,436.971680,115.447609,125.051125,95.522781,89.334358,99.174316,57.634308,80.499588,239.769363,49.132114,44.406693,93.053543,66.620720,108.270706,335.127075,0.00015,72.707855,12.920289,36.065514,74.034500,222.900192,27.512049,29.895000,31.303852,247.522171,72.145126,16.677626,58.998676,34.884548,39.532982,142.456863,77.326538,558.899597,137.325790,67.593826,34.820026,179.762955,113.639999,60.168900,170.221283,17.748697,158.308609,39.720001,25.910000,489.355530,199.672913,160.205460,356.805023,41.666088,325.500000,208.983231,29.280001,219.800003,111.608673,286.829987,10.760579,217.759995,99.959999,35.296616,32.329601,10.38,87.273994,64.956070,40.092834,151.986130,29.301939,46.641022,45.751163,239.890869,65.804070,99.000572,66.300003,145.725311
2023-01-05,13.99,123.583099,150.183777,87.709999,105.945595,59.849552,19.753489,254.771591,328.440002,154.091797,78.578094,223.530472,80.581207,85.780655,59.290745,23.684870,68.009949,38.818501,60.675030,182.901764,69.659332,132.456833,23.123976,96.047768,62.330002,248.349380,298.834991,198.417953,83.120003,295.613281,286.805695,37.651260,60.461758,555.309448,53.545685,142.747162,2416.570068,204.990005,32.221272,49.625698,74.379166,38.218731,247.315811,51.750000,271.589996,44.019215,2126.088867,27.270861,84.208626,65.898109,31.615118,43.766663,45.759998,71.501244,42.785805,73.523987,40.395317,230.896393,216.917526,78.430000,52.693428,125.498108,173.350266,80.856888,36.306862,361.429993,293.900543,74.486656,37.254459,154.678299,223.767365,77.260002,15.107059,114.053505,27.234638,23.674639,90.092537,108.676392,159.492050,433.855927,73.572807,39.939011,135.582718,44.103264,30.062954,55.491913,57.678711,17.527456,83.046906,159.877563,55.425804,34.600372,11.432638,68.144012,403.138184,38.931156,94.467232,235.969070,90.449883,224.282471,90.798302,91.205811,142.559998,47.576427,108.591553,94.151573,54.762188,141.682953,88.061684,331.015045,59.565403,251.560165,460.796631,90.682251,35.107426,114.380241,20.919876,27.850273,631.530273,76.809479,9.845435,152.511551,44.538193,39.274261,10.032943,121.589424,38.619503,173.974564,37.900280,0.00140,99.400002,64.571716,30.398970,35.117077,0.0001,120.221222,36.899609,233.016037,56.352474,79.412010,78.288925,32.247181,34.272770,18.011665,86.459343,159.659256,100.168716,325.319122,37.465336,12.915506,246.106720,299.591034,137.215286,73.947350,195.869980,15.531319,25.390989,210.671021,478.922882,71.054138,128.884491,99.784584,101.115669,44.442848,26.575493,370.068298,207.050003,268.619995,209.258865,62.106987,166.873016,128.650665,31.967382,61.747036,33.489578,15.828272,37.721676,46.523445,364.916901,125.958069,15.950824,63.340000,58.510647,42.884689,58.738125,88.076942,197.107864,352.502197,452.626587,26.900257,141.499847,192.146194,37.332344,31.877308,77.978447,2.060341,347.114288,145.548767,250.290726,65.765678,370.165710,271.381134,62.992290,74.857788,856.090027,67.641167,126.456940,16.607679,55.376404,35.150002,1353.829956,160.820267,93.240532,38.288364,298.540009,42.280941,110.183800,27.169323,107.609650,173.509995,79.280869,218.282867,26.719475,136.087570,54.102474,78.087090,48.020752,309.700012,117.072548,511.387817,366.320007,234.698807,68.914284,85.247314,133.328079,14.254633,148.515411,56.562027,57.683331,81.843864,834.289978,60.507568,9.797133,17.920076,59.642948,15.605412,95.430000,57.026222,166.815857,44.039974,78.642120,142.189423,127.949951,289.592834,16.030001,106.294228,90.930000,145.223221,117.663513,27.223005,89.023163,95.036087,76.269997,104.488480,722.831116,19.736637,138.960999,103.987610,430.240479,115.868416,122.389206,95.560684,88.392624,99.145844,59.111168,80.267799,223.636154,50.053928,43.547153,92.695053,64.663712,104.928558,329.692352,0.00020,71.507301,13.014660,35.670273,73.317253,201.223434,27.945673,29.775000,30.244627,244.904694,72.220886,16.738619,57.605850,36.477230,39.171589,143.893372,78.091492,553.946411,141.760712,67.498665,34.077099,180.070175,110.339996,60.028992,167.916641,17.587101,156.212418,41.240002,25.549999,475.251953,193.794540,157.247574,354.933350,41.340218,329.500000,207.508804,29.350000,221.600006,118.111870,287.890015,10.843000,219.520004,100.040001,35.785774,30.346182,10.86,85.091682,63.587879,39.876617,149.051224,29.003036,46.482044,45.460243,239.842209,64.472534,101.215599,64.709999,142.291504
2023-01-06,14.18,128.130249,152.994736,88.519997,107.408569,60.762417,19.715590,260.807129,332.750000,159.717438,80.182671,229.778198,82.755051,88.296089,60.927513,24.197567,70.235725,39.957829,61.668610,188.375870,71.239105,134.386566,24.008041,102.276367,63.959999,256.110901,310.962585,204.376175,86.080002,302.483185,294.749756,38.569233,61.787209,585.298706,56.768929,146.393112,2486.639893,213.000000,32.542824,45.736450,75.775307,39.132160,251.219635,53.180000,279.250000,44.709202,2160.097412,28.369267,86.332207,66.887680,32.767448,44.678471,46.330002,73.956512,43.298317,75.462357,41.951603,239.141312,222.060043,80.919998,53.550919,129.920609,178.373779,81.926346,37.356506,367.730011,292.441620,75.852341,38.115158,159.544174,230.554489,78.660004,15.611249,118.078941,28.183811,24.826500,93.054710,110.035202,162.064194,465.350189,76.575394,41.292713,139.729538,45.457973,31.317602,57.593224,59.603283,17.994476,84.102783,161.081818,55.795547,35.386070,11.715157,69.682480,414.550079,40.407631,97.779037,238.988159,91.694290,221.874710,92.773903,94.274513,145.830002,49.473728,111.255585,95.902191,55.726925,146.212372,90.408997,339.973907,61.382927,254.102982,463.212646,93.488319,35.913982,117.221802,21.234142,28.627050,644.263672,78.689590,10.026993,156.295242,46.265411,40.091324,10.303218,125.308586,40.984745,178.283630,38.527702,0.00140,102.180000,65.622833,31.628508,36.737160,0.0001,126.279190,37.802296,236.473816,56.866283,81.474777,79.726524,33.175499,35.163864,18.261026,87.844376,161.809265,103.302063,329.407318,38.677307,13.223451,250.256012,301.547363,140.061356,75.693382,201.426041,16.154457,26.464109,213.098053,483.358551,72.844353,131.250092,102.041351,103.679146,46.093475,27.703699,380.807220,205.360001,270.390015,216.974167,64.131706,168.226288,131.112473,32.048588,63.311237,34.410091,16.298508,38.871674,47.289017,388.484558,128.662354,16.274920,65.779999,59.639465,43.435467,59.988079,89.842598,197.155624,356.450317,448.992828,27.547729,139.633240,192.337616,39.857513,33.350903,80.822006,2.096173,363.392609,149.948059,257.269806,69.258575,382.041138,284.141602,64.733871,75.634155,873.469971,68.554237,129.525223,16.940205,57.157948,37.200001,1383.989990,165.485931,96.091743,39.199795,301.700012,44.210972,111.221550,27.688643,108.745979,180.350006,80.794136,220.855408,27.672712,139.763367,56.139603,79.051018,49.408581,315.549988,120.867546,504.517944,366.529999,242.579636,71.512917,88.191040,140.021240,14.848201,154.436310,57.177711,59.231522,83.154381,842.520020,61.995464,10.041851,18.275402,61.192268,15.834610,95.959999,58.444412,170.583603,45.157379,81.503029,145.575348,130.946136,299.744568,16.469999,109.873482,93.338104,149.633606,122.815048,27.893335,90.428696,97.508385,76.480003,110.161797,736.203979,20.392403,139.305588,106.828484,438.576691,118.970627,125.158401,97.057365,90.425285,101.291473,61.444988,81.648888,231.540771,51.793037,44.303928,96.183098,65.812195,106.224319,341.228821,0.00020,72.473373,13.254877,37.656349,75.152267,206.575119,28.942083,30.135000,31.020130,251.208176,74.531357,17.017452,58.176388,38.050602,40.423248,149.387512,80.095818,532.124268,145.773743,69.563683,35.677921,186.138138,113.059998,61.623913,174.313004,18.053938,163.914047,42.240002,26.400000,475.290802,202.316254,161.869827,367.850128,41.919552,316.500000,214.035553,28.730000,216.399994,119.016907,290.209991,11.081108,214.399994,97.599998,36.206276,31.570726,11.32,87.264778,65.843048,40.233841,154.485168,29.492155,47.620819,46.984432,246.645065,66.381386,102.438972,68.989998,144.433945
2023-01-09,14.61,128.654144,148.502716,89.239998,107.236465,59.592808,19.819805,265.205444,341.980011,161.242065,79.641586,229.156265,83.776360,89.594971,61.443340,24.948307,67.962395,40.084423,61.018959,188.120804,71.030464,133.093765,24.127760,104.453911,67.239998,251.383301,310.904480,205.124496,87.360001,301.498993,296.165680,38.839218,62.738079,610.327637,55.655605,146.617294,2441.750000,208.570007,32.051041,42.196484,74.881042,39.132160,244.545364,51.889999,274.720001,44.886364,2189.000977,28.918478,86.577240,65.064308,33.328835,44.928776,45.590000,75.226151,43.508812,74.435585,42.311493,236.988800,216.869003,81.760002,53.126884,129.626389,179.094193,82.416916,36.872055,367.179993,292.789459,74.666847,38.441311,160.191116,230.923157,77.589996,15.583239,118.812576,28.634901,25.122435,93.418999,109.225502,161.340439,461.379669,76.753166,41.358978,146.282944,45.702572,31.259251,58.663155,59.700985,18.118378,84.001785,159.822800,55.543041,36.112846,11.715157,70.653633,416.231750,40.274273,98.576141,231.767365,90.900604,224.124298,93.613525,94.051338,143.970001,49.707516,112.205688,95.911316,56.609741,146.955856,90.307350,341.221985,62.227440,252.003220,458.565735,92.829765,36.339424,117.479309,21.505941,28.077621,651.165710,78.607048,10.159037,156.081802,46.600544,40.531994,10.393308,128.347412,41.517902,182.093643,38.554977,0.00310,102.070000,66.285690,31.399118,36.322929,0.0001,124.203308,37.894409,233.578064,57.443321,78.718262,79.035851,33.212997,35.173653,18.193890,88.482079,161.401978,104.569160,334.063416,38.898540,13.051364,245.605225,301.813263,140.568207,73.726700,201.809219,16.012833,26.725391,212.852539,472.730499,74.011444,131.113068,102.372101,104.960892,45.730907,28.262978,390.284485,208.490005,264.929993,216.983704,63.778320,163.867783,130.570663,31.579409,62.376213,34.191822,16.138805,38.515720,48.722019,398.978607,127.333466,16.388792,67.070000,58.896324,43.862793,58.500038,89.495110,192.269318,343.574707,435.472961,26.838457,140.229416,190.873322,40.498421,34.029396,81.934311,2.087215,366.654266,149.117096,255.150284,70.238884,377.993591,285.210632,63.991558,72.528717,897.309998,66.467232,128.977325,16.977148,56.341404,37.639999,1363.219971,164.934174,96.144814,38.803154,296.399994,44.655636,110.212357,27.705126,104.522644,183.949997,80.867958,223.005707,27.730482,138.237198,55.734154,79.447929,48.967854,315.170013,121.178131,479.351044,378.559998,241.100189,71.087517,87.762520,137.238907,15.616641,155.732727,57.730930,60.228062,84.206711,828.710022,62.316380,10.075605,18.774782,60.868996,15.904366,95.519997,59.237484,168.916382,42.913700,80.953209,143.797256,128.416885,300.686890,16.270000,109.317757,92.264839,149.697372,123.168671,28.088852,87.966759,94.104355,77.080002,109.464561,679.616638,20.119169,137.793442,107.303574,438.319672,116.191360,124.544098,94.348167,91.525543,99.440132,63.067730,82.508453,231.746964,52.876415,44.014294,97.084183,65.692741,105.732826,343.681335,0.00015,73.687996,13.400723,39.098965,75.366516,207.809357,29.089703,30.004999,30.537807,255.864746,74.995331,16.830059,58.194504,38.176086,40.370361,145.842896,78.924210,543.154724,145.970001,71.295639,36.164356,181.577560,119.769997,61.288139,173.902847,18.071890,165.336411,43.349998,27.400000,475.349060,201.791397,164.348328,366.543732,42.191105,320.000000,214.871048,28.670000,217.600006,119.968605,283.230011,10.998688,215.520004,97.320000,36.060703,31.346518,11.61,88.913025,65.361801,39.848423,153.274399,29.555561,47.027103,46.155926,248.231445,67.023880,100.529793,69.059998,143.866547

In [23]:
returns = prc_df_2023.pct_change().dropna()

In [24]:
returns

Ticker,AAL,AAPL,ABBV,ABNB,ABT,ACGL,ACI,ACN,ADBE,ADI,ADM,ADP,AEE,AEP,AER,AES,AFL,AGR,AIG,AJG,ALC,ALL,ALLY,AMAT,AMD,AMGN,AMP,AMT,AMZN,AON,APD,APH,APO,ASML,AVGO,AXP,AZO,BA,BAC,BAX,BBY,BCE,BDX,BHF,BIIB,BK,BKNG,BKR,BMO,BMY,BN,BNS,BSX,BX,C,CAH,CARR,CAT,CB,CBRE,CCEP,CCI,CDW,CEG,CFG,CHTR,CI,CL,CM,CME,CMI,CNC,CNH,CNI,CNP,CNQ,COF,COP,COR,COST,CP,CRH,CRM,CSCO,CSX,CTSH,CTVA,CVE,CVS,CVX,D,DAL,DB,DD,DE,DELL,DFS,DG,DHI,DHR,DIS,DLR,DLTR,DOW,DTE,DUK,DVN,ECL,ED,EG,EIX,EL,ELV,EMR,ENB,EOG,EPD,EQH,EQIX,ES,ET,ETN,ETR,EXC,F,FANG,FCX,FDX,FE,FERN,FI,FIS,FITB,FNF,FNRC,FRCB,FTS,GD,GE,GILD,GIS,GLW,GM,GOLD,GOOG,GPC,GPN,GS,HAL,HBAN,HCA,HD,HES,HIG,HON,HPE,HPQ,HSY,HUM,IBKR,IBM,ICE,IFF,IMO,INTC,INTU,IQV,ISRG,ITW,JCI,JNJ,JPM,JXN,K,KDP,KEY,KHC,KKR,KLAC,KMB,KMI,KMX,KO,KR,L,LEN,LHX,LLY,LMT,LNC,LNG,LOW,LRCX,LUV,LYB,LYG,MA,MAR,MCD,MCHP,MCK,MCO,MDLZ,MDT,MELI,MET,META,MFC,MGA,MGM,MKL,MMC,MMM,MO,MOH,MOS,MPC,MPLX,MRK,MRNA,MS,MSFT,MT,MTB,MU,NEE,NEM,NFLX,NKE,NOC,NOW,NSC,NTR,NTRS,NUE,NVDA,NXPI,O,OKE,ORCL,ORLY,OXY,PAA,PARA,PCAR,PCG,PDD,PEG,PEP,PFE,PFG,PG,PGR,PH,PHG,PLD,PM,PNC,PPG,PPL,PRU,PSX,PYPL,QCOM,REGN,RF,RGA,RJF,ROP,ROST,RSG,RTX,RY,SBUX,SCCO,SCHW,SHW,SLB,SLF,SNX,SO,SPG,SPGI,SPRV,SRE,STLA,STM,STT,STZ,SU,SVXY,SYF,SYK,SYY,T,TD,TECK,TFC,TGT,TJX,TMO,TMUS,TRGP,TRP,TRV,TSLA,TSN,TT,TU,TXN,UAL,UBER,UNH,UNP,UPS,URI,USB,UVXY,V,VIXM,VIXY,VLO,VRTX,VTRS,VXX,VXZ,VZ,WBA,WBD,WEC,WELL,WFC,WM,WMB,WMT,WRB,WTW,XEL,XOM,XYZ,ZTS
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-01-04,0.066719,0.010314,0.008067,0.044994,0.014875,0.004963,0.009662,-0.003404,0.013327,0.021299,-0.036364,0.004713,0.005311,0.006851,0.026402,-0.029527,0.004750,0.013444,0.014778,0.013244,0.018701,0.016830,0.033579,0.026672,0.009997,0.010472,0.007146,0.020170,-0.007924,0.011021,0.000065,0.014790,0.024678,0.038685,0.012214,0.023246,0.005923,0.042223,0.018801,0.025274,0.019027,0.019746,0.007456,0.021552,-0.006676,0.024622,0.038495,-0.029913,0.028449,0.004982,0.042459,0.032935,0.010650,0.024694,0.025776,0.003519,0.010094,0.010382,0.016442,0.016318,0.023915,0.036440,0.009136,0.018313,0.028333,0.036360,-0.034777,0.006445,0.024679,0.006689,-0.002406,-0.003511,0.003724,0.015188,0.003045,0.002301,0.030440,0.001945,-0.008643,0.007236,0.024172,0.048014,0.035688,-0.000210,0.012953,0.008161,0.012897,-0.006575,-0.010010,-0.010633,0.003811,0.054584,0.065756,0.024252,-0.001909,0.000978,0.044128,-0.013051,0.010587,0.015633,0.033832,0.007974,0.001854,0.025274,0.014424,0.010704,0.013421,0.017322,0.008667,0.023127,0.032825,0.031507,-0.033373,-0.007179,0.018960,-0.000723,0.004540,0.037413,0.026626,0.013180,0.003442,0.006783,0.000733,0.013207,0.028254,-0.005785,0.028481,0.023580,0.007376,0.035714,0.008398,0.010651,0.025123,0.019571,0.0,0.018512,0.011111,-0.013596,0.058204,0.001288,0.008051,0.048249,0.025724,0.058889,-0.011037,0.012544,0.032735,0.004275,0.020446,0.018440,0.023313,0.012092,0.015239,0.019509,-0.019879,0.022416,0.017570,-0.016128,-0.016724,0.010367,0.007418,0.006781,0.023855,-0.003243,0.035541,0.000997,0.019229,0.016451,0.002270,0.016373,0.010887,0.009325,0.015593,-0.007577,0.008157,0.026689,0.011280,0.030420,0.009773,-0.002188,0.012215,0.073879,-0.000477,0.011244,0.011606,0.017721,0.000000,-0.005178,-0.002157,0.021090,0.029602,0.011807,0.019696,0.031288,0.022741,0.022321,0.024078,0.014281,0.000227,0.024457,-0.000855,0.027634,0.007245,0.034628,0.013715,0.014414,0.021084,0.025252,0.033727,0.067909,0.019690,0.019460,0.021883,-0.002416,-0.016901,0.015013,-0.003065,0.007366,0.008458,-0.009107,0.010849,-0.043743,0.031919,0.011175,0.076037,0.007873,0.038927,0.049025,0.020716,-0.025688,0.021660,0.012919,0.005027,0.021163,0.045323,0.030318,0.018768,0.012696,0.007820,0.009078,-0.016629,0.000983,0.000000,0.083772,-0.002235,0.012755,0.077251,0.007413,-0.002453,-0.022044,0.014803,0.004355,0.008453,0.017583,0.039642,0.037892,-0.000691,0.026392,0.024677,0.025000,0.017089,-0.003464,0.041700,0.040392,0.008356,0.020494,0.004953,-0.005372,0.019058,0.018475,-0.003341,0.000298,0.022846,0.036001,0.025799,0.017208,0.020094,0.003884,0.024353,-0.005900,0.008484,0.030798,0.019244,0.000000,0.008653,0.032214,0.032532,0.013776,0.015642,-0.012910,0.015628,0.021920,0.026257,0.009080,0.021345,0.026656,-0.012568,0.027962,0.006525,0.010758,0.015800,0.006617,0.005379,0.009228,0.000588,0.051249,0.014308,0.016207,0.025947,0.036517,0.067455,0.021688,-0.027264,0.007997,0.010440,0.026072,0.031138,-0.041237,0.025170,-0.019752,-0.030009,-0.003499,0.002832,0.032513,-0.027162,-0.019616,0.025174,0.008067,0.088050,0.006585,0.028230,0.020579,-0.000764,0.006221,0.001114,-0.003307,0.005343,0.008563,0.002911,0.025681,0.014368
2023-01-05,0.029433,-0.010605,-0.001222,-0.011384,-0.003687,0.002708,-0.002392,-0.023613,-0.037990,-0.037490,-0.025003,-0.021568,-0.033274,-0.018216,0.004876,-0.051686,-0.005840,-0.018070,-0.005481,-0.017392,-0.002277,0.002734,-0.005150,-0.013997,-0.036035,0.009342,-0.013200,-0.031370,-0.023726,-0.007829,-0.015558,-0.010705,-0.021908,-0.009653,-0.009318,-0.023930,-0.011814,0.006629,-0.002050,0.004586,-0.005248,-0.003561,-0.010771,-0.007480,0.002880,-0.004848,0.016347,0.032628,-0.008971,-0.001804,-0.024316,-0.005687,-0.015914,-0.018203,-0.004472,-0.004935,-0.011896,-0.004475,-0.003743,-0.016182,0.004671,-0.018137,-0.017058,-0.011989,-0.004428,0.020989,-0.019691,-0.013812,-0.009634,-0.001940,-0.015554,-0.027687,0.000618,-0.023392,-0.022597,-0.005356,-0.018998,0.030263,0.001289,-0.013952,-0.028687,-0.018837,-0.023282,-0.014090,-0.011829,-0.008440,-0.010890,0.014341,-0.016634,0.018009,-0.027685,0.024426,-0.027243,0.004821,-0.020662,-0.001710,-0.016984,0.007885,0.007311,-0.041822,-0.000653,-0.053739,0.014517,0.011084,-0.024925,-0.014788,0.021562,-0.032919,-0.013459,0.003078,-0.022594,-0.002825,-0.025626,-0.004297,-0.004023,0.000161,0.011914,-0.009100,-0.028714,-0.018516,0.023156,-0.010200,-0.050820,-0.021724,0.019983,0.026183,0.021539,-0.000937,-0.015588,-0.034483,-0.026063,-0.015591,-0.009862,-0.010376,0.0,-0.026900,-0.021734,-0.002447,0.015527,0.004094,0.006199,0.008208,0.008936,-0.005297,-0.021869,-0.019600,-0.014496,-0.011332,0.013531,-0.006964,0.005706,-0.013324,0.030827,0.003385,-0.026519,0.001827,-0.000367,-0.000851,-0.008331,-0.003883,-0.010449,-0.012989,-0.008044,0.010412,-0.004335,-0.040734,-0.003513,-0.005111,-0.008786,-0.011702,-0.007384,-0.000222,0.007393,-0.000990,-0.009820,-0.013274,0.002182,-0.014553,-0.017779,-0.009283,-0.001097,-0.027334,-0.011443,0.004225,-0.001012,0.001816,-0.003866,-0.011512,0.001196,-0.009851,0.000691,-0.003079,-0.012782,-0.002677,0.011991,0.004367,-0.009517,-0.006539,-0.008435,-0.023873,0.000107,-0.026117,-0.008092,-0.011609,0.022270,-0.008061,-0.003376,-0.015873,0.003700,-0.010974,0.004325,-0.018143,-0.017499,-0.000881,-0.047810,0.032817,0.046573,0.004266,0.013918,-0.021707,-0.008425,-0.029638,0.009825,-0.002388,0.009410,-0.022014,-0.005824,0.000937,-0.004867,0.003932,-0.069900,-0.013631,0.035287,-0.001854,0.000365,-0.032816,-0.028172,-0.018883,0.006052,-0.002013,0.009132,0.018164,0.005195,0.008649,-0.004378,-0.013854,0.047990,-0.022236,-0.010449,-0.009376,-0.007293,-0.012416,0.002974,0.004076,-0.014145,-0.035140,-0.004050,-0.026629,-0.052781,-0.023054,-0.017197,0.023242,-0.018278,-0.019098,-0.003758,-0.010954,0.022319,0.016202,-0.015404,0.003645,-0.021287,0.000397,-0.010542,-0.000287,0.025625,-0.002879,-0.067286,0.018762,-0.019356,-0.003853,-0.029375,-0.030868,-0.016217,0.333333,-0.016512,0.007304,-0.010959,-0.009688,-0.097249,0.015761,-0.004014,-0.033837,-0.010575,0.001050,0.003657,-0.023608,0.045656,-0.009142,0.010084,0.009893,-0.008862,0.032295,-0.001408,-0.021336,0.001709,-0.029039,-0.002325,-0.013539,-0.009105,-0.013241,0.038268,-0.013894,-0.028821,-0.029440,-0.018463,-0.005246,-0.007821,0.012289,-0.007055,0.002391,0.008189,0.058268,0.003696,0.007660,0.008082,0.000800,0.013859,-0.061350,0.046243,-0.025005,-0.021063,-0.005393,-0.019310,-0.010201,-0.003409,-0.006359,-0.000203,-0.020235,0.022374,-0.023982,-0.023564
2023-01-06,0.013581,0.036794,0.018717,0.009235,0.013809,0.015253,-0.001919,0.023690,0.013123,0.036508,0.020420,0.027950,0.026977,0.029324,0.027606,0.021647,0.032727,0.029350,0.016375,0.029929,0.022679,0.014569,0.038232,0.064849,0.026151,0.031252,0.040583,0.030029,0.035611,0.023239,0.027698,0.024381,0.021922,0.054005,0.060196,0.025541,0.028996,0.039075,0.009980,-0.078372,0.018771,0.023900,0.015785,0.027633,0.028204,0.015675,0.015996,0.040278,0.025218,0.015017,0.036449,0.020833,0.012456,0.034339,0.011979,0.026364,0.038526,0.035708,0.023707,0.031748,0.016273,0.035240,0.028979,0.013227,0.028910,0.017431,-0.004964,0.018335,0.023103,0.031458,0.030331,0.018121,0.033374,0.035294,0.034852,0.048654,0.032879,0.012503,0.016127,0.072592,0.040811,0.033894,0.030585,0.030717,0.041734,0.037867,0.033367,0.026645,0.012714,0.007532,0.006671,0.022708,0.024712,0.022577,0.028308,0.037925,0.035058,0.012794,0.013758,-0.010735,0.021758,0.033646,0.022938,0.039879,0.024533,0.018594,0.017617,0.031969,0.026655,0.027065,0.030513,0.010108,0.005243,0.030944,0.022974,0.024843,0.015022,0.027891,0.020163,0.024478,0.018441,0.024809,0.038781,0.020804,0.026939,0.030588,0.061245,0.024768,0.016555,0.000000,0.027968,0.016278,0.040447,0.046134,0.0,0.050390,0.024463,0.014839,0.009118,0.025976,0.018363,0.028788,0.026000,0.013844,0.016019,0.013466,0.031281,0.012567,0.032349,0.023843,0.016860,0.006530,0.020742,0.023612,0.028366,0.040121,0.042264,0.011520,0.009262,0.025195,0.018354,0.022616,0.025352,0.037140,0.042453,0.029019,-0.008162,0.006589,0.036870,0.032601,0.008110,0.019136,0.002540,0.025332,0.027487,0.029709,0.030486,0.016456,0.064584,0.021470,0.020318,0.038522,0.019293,0.012843,0.021280,0.020047,0.000242,0.011200,-0.008028,0.024069,-0.013192,0.000996,0.067640,0.046227,0.036466,0.017391,0.046896,0.030226,0.027884,0.053111,0.032081,0.047020,0.027648,0.010371,0.020302,0.013499,0.024263,0.020022,0.032172,0.058321,0.022278,0.029012,0.030579,0.023804,0.010585,0.045648,0.009418,0.019114,0.010560,0.039421,0.019087,0.011785,0.035676,0.027011,0.037653,0.012344,0.028901,0.018889,0.032416,-0.013434,0.000573,0.033578,0.037708,0.034532,0.050201,0.041640,0.039867,0.010885,0.026839,0.016012,0.009865,0.024590,0.024978,0.019828,0.025977,0.014687,0.005554,0.024869,0.022586,0.025373,0.036379,0.023813,0.023417,0.035055,0.027448,0.033673,0.026483,0.030370,0.043782,0.024624,0.015788,0.026014,0.002753,0.054296,0.018501,0.033226,0.002480,0.027319,0.019376,0.026774,0.022626,0.015662,0.022996,0.021641,0.039482,0.017206,0.035346,0.034745,0.017378,0.037629,0.017761,0.012349,0.034992,0.000000,0.013510,0.018457,0.055679,0.025028,0.026596,0.035655,0.012091,0.025641,0.025739,0.031992,0.016658,0.009904,0.043133,0.031953,0.038182,0.025666,-0.039394,0.028308,0.030593,0.046976,0.033698,0.024651,0.026569,0.038092,0.026544,0.049302,0.024248,0.033268,0.000082,0.043973,0.029395,0.036392,0.014014,-0.039454,0.031453,-0.021124,-0.023466,0.007663,0.008059,0.021960,-0.023324,-0.024390,0.011751,0.040353,0.042357,0.025538,0.035465,0.008958,0.036457,0.016864,0.024499,0.033528,0.028364,0.029607,0.012087,0.066141,0.015057
2023-01-09,0.030324,0.004089,-0.029361,0.008134,-0.001602,-0.019249,0.005286,0.016864,0.027739,0.009546,-0.006748,-0.002707,0.012341,0.014711,0.008466,0.031025,-0.032367,0.003168,-0.010535,-0.001354,-0.002929,-0.009620,0.004987,0.021291,0.051282,-0.018459,-0.000187,0.003661,0.014870,-0.003254,0.004804,0.007000,0.015389,0.042763,-0.019611,0.001531,-0.018052,-0.020798,-0.015112,-0.077399,-0.011802,0.000000,-0.026567,-0.024257,-0.016222,0.003963,0.013381,0.019359,0.002838,-0.027260,0.017132,0.005602,-0.015972,0.017167,0.004862,-0.013606,0.008579,-0.009001,-0.023377,0.010381,-0.007918,-0.002265,0.004039,0.005988,-0.012968,-0.001496,0.001189,-0.015629,0.008557,0.004055,0.001599,-0.013603,-0.001794,0.006213,0.016005,0.011920,0.003915,-0.007359,-0.004466,-0.008532,0.002322,0.001605,0.046901,0.005381,-0.001863,0.018577,0.001639,0.006886,-0.001201,-0.007816,-0.004526,0.020538,0.000000,0.013937,0.004057,-0.003300,0.008152,-0.030214,-0.008656,0.010139,0.009050,-0.002367,-0.012755,0.004725,0.008540,0.000095,0.015842,0.005085,-0.001124,0.003671,0.013758,-0.008263,-0.010032,-0.007044,0.011846,0.002197,0.012800,-0.019193,0.010713,-0.001049,0.013169,-0.001366,0.007244,0.010992,0.008744,0.024251,0.013009,0.021371,0.000708,1.214286,-0.001077,0.010101,-0.007253,-0.011276,0.0,-0.016439,0.002437,-0.012246,0.010147,-0.033833,-0.008663,0.001130,0.000278,-0.003677,0.007259,-0.002517,0.012266,0.014135,0.005720,-0.013014,-0.018584,0.000882,0.003619,-0.025982,0.001902,-0.008767,0.009873,-0.001152,-0.021988,0.016022,-0.001044,0.003241,0.012363,-0.007866,0.020188,0.024887,0.015242,-0.020193,0.000044,-0.005510,-0.025909,-0.004132,-0.014640,-0.014769,-0.006343,-0.009799,-0.009157,0.030303,0.027013,-0.010328,0.006997,0.019611,-0.012461,0.009838,-0.024806,-0.003868,-0.024784,-0.036122,-0.030112,-0.025747,0.004270,-0.007613,0.016080,0.020344,0.013762,-0.004273,0.008976,-0.005542,-0.008239,0.014154,-0.010595,0.003762,-0.011467,-0.041059,0.027293,-0.030443,-0.004230,0.002181,-0.014286,0.011828,-0.015007,-0.003334,0.000552,-0.010118,-0.017567,0.010058,-0.009074,0.000595,-0.038837,0.019961,0.000914,0.009736,0.002088,-0.010920,-0.007222,0.005021,-0.008920,-0.001204,0.002570,-0.049883,0.032821,-0.006099,-0.005949,-0.004859,-0.019871,0.051753,0.008395,0.009675,0.016824,0.012655,-0.016391,0.005176,0.003361,0.027325,-0.005283,0.004405,-0.004585,0.013570,-0.009774,-0.049686,-0.006746,-0.012214,-0.019315,0.003144,-0.012143,-0.005058,-0.011499,0.000426,0.002879,0.007009,-0.027225,-0.034910,0.007845,-0.006329,-0.076864,-0.013399,-0.010855,0.004447,-0.000586,-0.023361,-0.004908,-0.027913,0.012168,-0.018277,0.026410,0.010528,0.000891,0.020917,-0.006537,0.009368,-0.001815,-0.004627,0.007187,-0.250000,0.016760,0.011003,0.038310,0.002851,0.005975,0.005101,-0.004314,-0.015549,0.018537,0.006225,-0.011012,0.000311,0.003298,-0.001308,-0.023728,-0.014628,0.020729,0.001346,0.024897,0.013634,-0.024501,0.059349,-0.005449,-0.002353,0.000994,0.008677,0.026278,0.037879,0.000123,-0.002594,0.015312,-0.003551,0.006478,0.011058,0.003904,-0.002088,0.005545,0.007996,-0.024051,-0.007438,0.005224,-0.002869,-0.004021,-0.007102,0.025618,0.018888,-0.007309,-0.009579,-0.007837,0.002150,-0.012468,-0.017634,0.006432,0.009679,-0.018637,0.001015,-0.003928
2023-01-10,0.039699,0.004456,-0.012495,-0.007844,0.015158,0.006383,0.018165,0.004310,-0.009591,0.012687,0.010074,0.005303,-0.003243,-0.006840,-0.020827,-0.000734,0.007698,-0.009249,-0.006576,0.004798,0.008952,0.008928,0.019466,0.014555,0.012046,0.013920,-0.004514,0.012084,0.028732,0.003264,0.003208,0.002275,0.018371,0.019410,-0.003398,0.010638,-0.002551,-0.009014,0.006786,0.023266,0.026932,-0.001527,0.011567,-0.000578,0.024534,-0.002701,0.005678,0.010805,-0.003250,0.009013,-0.005024,0.001393,0.010309,-0.000621,0.013673,0.007219,0.011494,0.015773,0.005638,0.011864,-0.006740,0.011831,0.013155,-0.010952,0.003893,0.020317,0.002475,-0.005335,-0.000943,0.009670,0.014041,-0.018946,0.008388,-0.012593,0.002954,0.003806,0.010775,0.006135,0.013881,0.005535,-0.016214,-0.002060,0.002311,0.004735,0.008090,0.005751,0.010473,-0.014203,-0.009181,0.004909,0.003897,0.035899,0.015273,0.005988,0.021555,0.004967,0.016654,0.002945,0.008731,0.046422,0.008336,0.011667,0.013267,0.021527,-0.003653,0.002282,0.014952,0.013181,0.003786,0.017749,0.006048,0.003134,-0.000064,0.005758,-0.000488,-0.001096,0.001975,0.008772,0.020539,-0.000233,0.006499,-0.002921,-0.006731,-0.010419,0.011820,0.003251,0.043894,-0.005270,0.004481,0.096774,-0.010091,-0.014286,0.007013,0.014698,0.0,0.018321,0.000729,0.009502,0.035778,0.023972,-0.007440,0.011858,0.033129,0.022140,0.004955,-0.003873,-0.010802,0.012351,0.012364,0.004164,0.002442,0.008873,-0.004161,-0.008458,0.003180,0.005896,0.015712,-0.002706,-0.000249,0.014299,0.008708,0.013398,0.041483,-0.003130,0.004436,-0.016846,0.033671,0.024271,0.002291,0.007936,-0.002392,0.008954,0.031429,-0.008826,-0.009437,0.001099,0.003081,0.009871,0.019445,-0.008466,0.001603,0.004771,-0.007666,-0.004546,0.001187,0.013432,0.004377,0.008347,0.007190,0.026427,0.021047,0.009828,0.013660,0.016849,0.003722,0.004292,0.000108,0.004130,0.006211,0.022358,0.001859,0.022215,0.001041,0.017410,0.020584,0.003224,0.027188,0.002721,0.006094,0.032147,0.006199,0.000000,0.010569,0.000217,-0.014845,-0.050212,0.006393,-0.004760,0.003896,0.030987,0.014605,0.007617,0.029514,-0.003702,0.015082,0.005591,0.017809,0.039249,0.007930,0.000767,0.006023,0.001652,-0.033173,0.006687,0.071525,0.017981,0.031683,-0.008655,0.023933,0.000926,-0.002208,0.001092,0.001675,0.017391,0.007015,-0.001253,-0.014971,0.002835,-0.008253,-0.015913,0.008634,-0.000987,0.007651,0.003166,0.017210,-0.000086,-0.001075,0.004018,0.007061,0.000000,0.011093,-0.004313,0.010898,0.020068,0.027128,-0.002716,0.017294,0.002711,0.000113,0.008928,-0.020042,0.003213,0.008252,0.012030,0.038161,0.002224,-0.008093,0.005751,-0.004670,0.047305,-0.005454,-0.012424,0.011560,0.333333,0.002418,0.016005,0.014910,0.006798,0.020835,-0.015541,0.023163,0.017033,0.010766,0.009596,0.022584,-0.003268,-0.000253,0.004367,-0.002430,0.011410,0.040176,0.005310,-0.007074,-0.002445,0.011104,-0.007681,-0.001978,0.004773,-0.001490,0.009735,0.055363,0.023358,-0.008285,0.003878,-0.016071,0.014548,0.001073,-0.062500,0.011391,-0.025113,-0.042279,0.026676,0.019489,-0.014155,-0.041574,-0.022195,0.014020,0.009628,0.081826,0.001657,-0.004042,-0.000708,-0.021044,-0.015017,-0.000621,0.005070,-0.006587,0.001806,0.014935,0.014046,0.049640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...

## 2024

In [12]:
prc_df_2024 = pd.read_parquet('data/original_data/prc_df_2024.parquet')
prc_df_2024 = prc_df_2024.dropna(axis=1)

In [13]:
prc_df_2024

Ticker,AAL,AAPL,ABBV,ABNB,ABT,ACGL,ACI,ACN,ADBE,ADI,...,WBD,WELL,WFC,WM,WMB,WMT,XEL,XOM,XYZ,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2024-01-02,13.44,184.532089,152.743393,134.479996,107.138489,71.840385,22.120523,341.431366,580.070007,190.350952,...,11.66,87.767197,47.823627,177.070602,33.995880,52.467777,61.121792,98.105995,72.220001,194.055588
2024-01-03,12.95,183.150391,153.355057,133.419998,106.816628,73.162132,22.004251,332.573761,571.789978,185.808029,...,11.30,86.473648,47.193474,176.005859,34.751980,52.471069,61.227722,98.930260,68.629997,190.462128
2024-01-04,13.09,180.824341,154.310791,133.720001,108.240601,73.666107,21.839539,331.756866,567.049988,182.966232,...,11.35,86.269402,47.775150,176.262207,34.283009,51.963818,61.372169,98.067657,68.150002,191.557953
2024-01-05,13.60,180.098709,154.960678,135.979996,108.065041,73.038513,22.323997,331.294312,564.599976,183.438232,...,11.20,86.094337,48.395611,175.256622,34.024590,51.617966,61.372169,98.364784,66.959999,192.357574
2024-01-08,14.58,184.452576,154.282104,140.080002,109.625542,73.333298,22.275551,334.965271,580.549988,185.827698,...,11.40,87.348984,48.395611,175.719986,34.120300,52.125221,61.227722,96.725830,69.309998,193.640945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-24,15.31,247.100006,204.080002,144.820007,134.949997,89.550003,20.430000,363.910004,444.420013,236.990005,...,11.09,149.970001,77.220001,229.679993,57.330002,93.669998,70.779999,111.269997,65.919998,165.309998
2025-02-25,15.13,247.039993,204.139999,141.550003,135.820007,90.349998,20.650000,362.950012,443.410004,235.300003,...,10.69,151.740005,76.000000,230.750000,56.180000,97.690002,70.449997,109.730003,62.840000,168.529999
2025-02-26,15.18,240.360001,203.009995,144.029999,135.960007,89.570000,20.690001,358.350006,441.500000,233.729996,...,10.50,150.649994,76.449997,228.690002,56.900002,96.199997,69.970001,109.459999,65.290001,164.990005
2025-02-27,14.53,237.300003,205.020004,139.449997,135.869995,92.099998,20.820000,356.869995,437.190002,223.850006,...,11.00,151.520004,76.620003,229.610001,56.259998,96.790001,70.760002,110.150002,64.279999,164.979996
2025-02-28,14.35,241.839996,209.029999,138.869995,138.009995,92.910004,21.040001,348.500000,438.559998,230.059998,...,11.46,153.509995,78.320000,232.779999,58.180000,98.610001,72.099998,111.330002,65.300003,167.240005

In [14]:
returns_2024 = prc_df_2024.pct_change().dropna()

In [15]:
returns_2024

Ticker,AAL,AAPL,ABBV,ABNB,ABT,ACGL,ACI,ACN,ADBE,ADI,...,WBD,WELL,WFC,WM,WMB,WMT,XEL,XOM,XYZ,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2024-01-03,-0.036458,-0.007488,0.004005,-0.007882,-0.003004,0.018398,-0.005256,-0.025943,-0.014274,-0.023866,...,-0.030875,-0.014738,-0.013177,-0.006013,0.022241,0.000063,0.001733,0.008402,-0.049709,-0.018518
2024-01-04,0.010811,-0.012700,0.006232,0.002249,0.013331,0.006888,-0.007486,-0.002456,-0.008290,-0.015294,...,0.004425,-0.002362,0.012325,0.001456,-0.013495,-0.009667,0.002359,-0.008719,-0.006994,0.005754
2024-01-05,0.038961,-0.004013,0.004212,0.016901,-0.001622,-0.008519,0.022183,-0.001394,-0.004321,0.002580,...,-0.013216,-0.002029,0.012987,-0.005705,-0.007538,-0.006656,0.000000,0.003030,-0.017462,0.004174
2024-01-08,0.072059,0.024175,-0.004379,0.030152,0.014440,0.004036,-0.002170,0.011081,0.028250,0.013026,...,0.017857,0.014573,0.000000,0.002644,0.002813,0.009827,-0.002354,-0.016662,0.035096,0.006672
2024-01-09,-0.013717,-0.002263,0.005451,-0.003926,0.002936,-0.012578,0.004785,0.007052,0.009732,0.004127,...,-0.032456,-0.002450,-0.012620,-0.000056,-0.006452,0.006698,-0.004876,-0.012386,0.003174,-0.001071
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-24,0.005253,0.006312,0.009897,-0.008558,0.000222,0.016113,-0.005839,-0.000961,0.000225,-0.008036,...,0.028757,0.013865,-0.003613,0.007236,-0.001915,-0.011711,0.012010,0.005240,-0.035552,0.030226
2025-02-25,-0.011757,-0.000243,0.000294,-0.022580,0.006447,0.008934,0.010768,-0.002638,-0.002273,-0.007131,...,-0.036069,0.011802,-0.015799,0.004659,-0.020059,0.042917,-0.004662,-0.013840,-0.046723,0.019479
2025-02-26,0.003305,-0.027040,-0.005535,0.017520,0.001031,-0.008633,0.001937,-0.012674,-0.004308,-0.006672,...,-0.017774,-0.007183,0.005921,-0.008927,0.012816,-0.015252,-0.006813,-0.002461,0.038988,-0.021005
2025-02-27,-0.042820,-0.012731,0.009901,-0.031799,-0.000662,0.028246,0.006283,-0.004130,-0.009762,-0.042271,...,0.047619,0.005775,0.002224,0.004023,-0.011248,0.006133,0.011291,0.006304,-0.015469,-0.000061
2025-02-28,-0.012388,0.019132,0.019559,-0.004159,0.015750,0.008795,0.010567,-0.023454,0.003134,0.027742,...,0.041818,0.013134,0.022187,0.013806,0.034127,0.018804,0.018937,0.010713,0.015868,0.013699

In [13]:
test = pd.read_csv('data/submission1.csv')

In [14]:
test

       ID    WEIGHT
0       V -0.028191
1     VXZ -0.028078
2     ADI -0.028023
3     SYF -0.027975
4    AMZN -0.027467
..    ...       ...
292   ALL  0.027636
293    ET  0.027835
294   HON  0.027951
295   ICE  0.028109
296  AMGN  0.028243

[297 rows x 2 columns]

In [15]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      297 non-null    object
 1   WEIGHT  297 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.8+ KB

In [16]:
test["WEIGHT"].sum()

1.0

In [17]:
submission = test.copy()
submission["WEIGHT"] = submission["WEIGHT"].apply(lambda x: int(x * 1000) / 1000)

In [18]:
submission["WEIGHT"].sum()

0.9659999999999997